"""
FinShield Policy & Rule Engine Definitions
"""
from app.rules.policy_config import (
    MIN_LIVING_COST_FLOOR_RATIO,
    TARGET_EMERGENCY_BUFFER_MONTHS,
    MAX_SAFE_DTI_RATIO,
    HARD_CONSOLIDATION_DTI_CEILING,
    MIN_SAVINGS_FOR_CONSOLIDATION_MONTHS,
    MAX_DISCRETIONARY_CUT_RATIO,
    SAFE_DISPOSABLE_CAPACITY_FACTOR,
    TIER_A_AUTO_EXECUTE_LEVELS,
    TIER_B_HUMAN_APPROVAL_LEVELS,
    TIER_C_HUMAN_ONLY_LEVELS
)

__all__ = [
    "MIN_LIVING_COST_FLOOR_RATIO",
    "TARGET_EMERGENCY_BUFFER_MONTHS",
    "MAX_SAFE_DTI_RATIO",
    "HARD_CONSOLIDATION_DTI_CEILING",
    "MIN_SAVINGS_FOR_CONSOLIDATION_MONTHS",
    "MAX_DISCRETIONARY_CUT_RATIO",
    "SAFE_DISPOSABLE_CAPACITY_FACTOR",
    "TIER_A_AUTO_EXECUTE_LEVELS",
    "TIER_B_HUMAN_APPROVAL_LEVELS",
    "TIER_C_HUMAN_ONLY_LEVELS"
]
